version: '2'
services:
  redis:
    # apt-get install -y procps
    image: redis/redis-stack:latest
    volumes:
      - ./data:/data
    ports:
      - "6379:6379"
      - "8001:8001"
  spring:
    build: .
    image: redis-session-spring
    links:
      - redis:redis
    ports:
      - "8080:8080"